name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          # - latest (aliases not yet supported, see https://github.com/actions/setup-node/issues/26)
          - 14
          - 12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - run: npm run coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - uses: rtCamp/action-slack-notify@v2
        if: ${{ always() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github
          SLACK_ICON: https://storage.googleapis.com/iten-img-dev/logo/github_inverted.png
          SLACK_USERNAME: Not GitHub
          SLACK_COLOR: ${{ (success() && '#2EB886') || '#DC143C' }}
